[[constraint]]
    name="github.com/nalej/derrors"
    version="=v2.0.0"

[[constraint]]
    name="github.com/rs/zerolog"
    version="v1.8.0"

[[constraint]]
    name="github.com/spf13/cobra"
    version="v0.0.3"

[[constraint]]
    name = "github.com/nalej/grpc-edge-inventory-proxy-go"
    version="=v0.0.16"

[[constraint]]
    name = "github.com/nalej/grpc-inventory-manager-go"
    version="=v0.0.56"

[[constraint]]
    name = "github.com/nalej/grpc-inventory-go"
    version="=v0.0.30"

[[constraint]]
    name = "github.com/nalej/grpc-edge-controller-go"
    version="=v0.0.18"

[[constraint]]
    name = "github.com/nalej/grpc-monitoring-go"
    version="=v0.0.5"

[[constraint]]
    name="github.com/nalej/grpc-network-go"
    version="v0.0.40"

[[constraint]]
    name="github.com/nalej/nalej-bus"
    version="=v0.3.0"
