###
# Application example
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: edge-inventory-proxy
  name: edge-inventory-proxy
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: edge-inventory-proxy
  template:
    metadata:
      labels:
        cluster: management
        component: edge-inventory-proxy
    spec:
      containers:
      - name: edge-inventory-proxy
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/edge-inventory-proxy:__NPH_VERSION
        imagePullPolicy: Always
        args:
        - "run"
        - "--debug"
        - "--port=5544"
        securityContext:
          runAsUser: 2000
      - name: eip-sidecar
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/eip-sidecar:__NPH_VERSION
        imagePullPolicy: Always
        args:
          - "run"
          - "--debug"
          - "--vpnAddress=vpn-server.__NPH_NAMESPACE.cluster.local:5555"
        securityContext:
          runAsUser: 0
      imagePullSecrets:
      - name: nalej-registry
