apiVersion: v1
kind: Service
metadata:
  name: edge-inventory-proxy
  namespace: __NPH_NAMESPACE
  labels:
    component: edge-inventory-proxy
spec:
  selector:
    cluster: management
    component: edge-inventory-proxy
  ports:
    - port: 5544
      protocol: TCP
      targetPort: 5544