###
# Application example
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: edge-inventory-proxy
  name: edge-inventory-proxy
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: edge-inventory-proxy
  template:
    metadata:
      labels:
        cluster: management
        component: edge-inventory-proxy
    spec:
      containers:
      - name: edge-inventory-proxy
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/edge-inventory-proxy:__NPH_VERSION
        imagePullPolicy: Always
        args:
        - "run"
        - "--debug"
        - "--port=5544"
        - "--queueAddress=broker.__NPH_NAMESPACE:6650"
        - "--dnsServer=$(DNS_SERVER)"
        - "--inventoryManagerAddress=inventory-manager.__NPH_NAMESPACE:5510"
        env:
        - name: DNS_SERVER
          valueFrom:
            configMapKeyRef:
              name: management-config
              key: dns_host
        securityContext:
          runAsUser: 2000
      - name: eip-sidecar
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/eip-sidecar:__NPH_VERSION
        imagePullPolicy: Always
        args:
            - "run"
            - "--debug"
            - "--vpnAddress=vpn-server.__NPH_NAMESPACE:5555"
            - "--networkManagerAddress=network-manager.__NPH_NAMESPACE:8000"
        securityContext:
          runAsUser: 0
          capabilities:
            add:
              - NET_ADMIN
              - SYS_ADMIN
        volumeMounts:
          - name: dev-net-tun
            readOnly: true
            mountPath: /dev/net/tun
      imagePullSecrets:
      - name: nalej-registry
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
